title: not sure yet
author: helloseven
email: helloseven@domain.com
description: > # this means to ignore newlines until "baseurl:"
  If I am not sure about the title of the site yet, I am definitely further from figuring out the description!

# social links
twitter_username: helloseven # DO NOT include the @ character, or else the build will fail!
github_username:  hellosevenh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
